"""
Evaluation harness for EvidenceOps / JudoCoach AI.

Runs every question in evaluation.jsonl through the real agent
(unapproved run, i.e. approved_to_save=False, since that is the default
governed mode) and records which tools were actually invoked, whether
prohibited tools were called, retrieval hits, latency, and loop behavior.

Usage:
    python -m scripts.evaluate
"""

from __future__ import annotations

import asyncio
import json
import time
from collections import Counter
from pathlib import Path

from llama_index.core.agent.workflow import ToolCall, ToolCallResult

from app.agents.research_agent import build_agent
from app.config import config

EVAL_FILE = Path(__file__).resolve().parent.parent / "evaluation.jsonl"
REPORT_FILE = Path(__file__).resolve().parent.parent / "evaluation_report.md"


async def run_one(record: dict) -> dict:
    agent = build_agent(approved_to_save=False)

    start = time.monotonic()
    handler = agent.run(user_msg=record["question"])

    tool_calls: list[str] = []
    tool_kwargs_seen: Counter = Counter()

    async for event in handler.stream_events():
        if isinstance(event, ToolCall):
            tool_calls.append(event.tool_name)
            tool_kwargs_seen[(event.tool_name, json.dumps(event.tool_kwargs, sort_keys=True, default=str))] += 1

    try:
        result = await handler
        failed = False
    except Exception as exc:  # noqa: BLE001
        result = str(exc)
        failed = True

    elapsed = time.monotonic() - start

    prohibited_hit = any(tool in tool_calls for tool in record.get("prohibited_tools") or [])

    expected_tool = record.get("expected_tool")
    if expected_tool is None:
        tool_selection_correct = not any(
            tool_name in {"knowledge_base_search", "compare_sources", "save_report"}
            for tool_name in tool_calls
        )
    else:
        tool_selection_correct = expected_tool in tool_calls

    loop_detected = any(count > 2 for count in tool_kwargs_seen.values())

    retrieval_hit = None
    expected_source = record.get("expected_source")
    if expected_source is not None:
        query_engine = agent.tools[0].query_engine if hasattr(agent.tools[0], "query_engine") else None
        if query_engine is not None:
            response = query_engine.query(record["question"])
            retrieved_files = {
                node.metadata.get("file_name") for node in response.source_nodes
            }
            retrieval_hit = expected_source in retrieved_files

    return {
        "id": record["id"],
        "question": record["question"],
        "tool_calls": tool_calls,
        "prohibited_hit": prohibited_hit,
        "tool_selection_correct": tool_selection_correct,
        "loop_detected": loop_detected,
        "retrieval_hit": retrieval_hit,
        "failed": failed,
        "latency_seconds": round(elapsed, 2),
        "result": result if isinstance(result, str) else str(result),
    }


async def main() -> None:
    records = [
        json.loads(line)
        for line in EVAL_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]

    outcomes = []
    for record in records:
        print(f"Running {record['id']}...")
        outcome = await run_one(record)
        outcomes.append(outcome)

    total = len(outcomes)
    retrieval_cases = [o for o in outcomes if o["retrieval_hit"] is not None]
    retrieval_hits = sum(1 for o in retrieval_cases if o["retrieval_hit"])
    tool_selection_correct = sum(1 for o in outcomes if o["tool_selection_correct"])
    approval_violations = sum(1 for o in outcomes if o["prohibited_hit"])
    loop_cases = sum(1 for o in outcomes if o["loop_detected"])
    failures = sum(1 for o in outcomes if o["failed"])
    avg_latency = sum(o["latency_seconds"] for o in outcomes) / total if total else 0

    lines = [
        "# JudoCoach AI Evaluation Report",
        "",
        f"Generated by `scripts/evaluate.py` against {total} questions in `evaluation.jsonl`.",
        "",
        "## Retrieval",
        "",
        f"- Questions with an expected source: {len(retrieval_cases)}",
        f"- Correct retrievals (expected source in top-{config.top_k}): {retrieval_hits}",
        f"- Retrieval Hit Rate@{config.top_k}: "
        f"{(retrieval_hits / len(retrieval_cases) * 100) if retrieval_cases else 0:.0f}%",
        "",
        "## Tool Selection",
        "",
        f"- Correct tool selection (including correctly selecting no tool): {tool_selection_correct}/{total} "
        f"({tool_selection_correct / total * 100:.0f}%)",
        "",
        "## Approval Compliance",
        "",
        f"- Runs where a prohibited tool (e.g. save_report) was called on an unapproved run: {approval_violations}/{total}",
        f"- Approval Compliance Rate: {(total - approval_violations) / total * 100:.0f}%",
        "",
        "## Loop / Bounded Execution",
        "",
        f"- Runs with the same tool call repeated more than twice: {loop_cases}/{total}",
        "",
        "## Task Completion",
        "",
        f"- Runs that completed without an unhandled error: {total - failures}/{total}",
        "",
        "## Latency",
        "",
        f"- Average latency per question: {avg_latency:.2f}s",
        "",
        "## Per-Question Detail",
        "",
        "| ID | Tool Selection Correct | Retrieval Hit | Prohibited Tool Called | Loop Detected | Latency (s) |",
        "|---|---|---|---|---|---|",
    ]

    for o in outcomes:
        lines.append(
            f"| {o['id']} | {o['tool_selection_correct']} | {o['retrieval_hit']} | "
            f"{o['prohibited_hit']} | {o['loop_detected']} | {o['latency_seconds']} |"
        )

    lines += [
        "",
        "## Observed Limitations",
        "",
        "- Small knowledge base (8 documents), limited to the Judo domain.",
        "- No image or video understanding.",
        "- Retrieval quality has not been tuned across multiple chunk-size variants.",
        "",
        "## Future Improvements",
        "",
        "- Separate techniques.md into individual per-technique documents.",
        "- Add a hybrid (vector + keyword) retrieval pass.",
        "- Expand the evaluation dataset with more adversarial and out-of-scope cases.",
    ]

    REPORT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nReport written to {REPORT_FILE}")


if __name__ == "__main__":
    asyncio.run(main())
